# Generated by Django 4.1.1 on 2023-07-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='bd', max_length=100),
        ),
    ]
