# Generated by Django 4.1.1 on 2023-07-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrations', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
                ('specialization', models.CharField(max_length=100)),
                ('certificate', models.CharField(max_length=100)),
                ('appointments', models.ManyToManyField(related_name='doctors', to='administrations.appointment')),
                ('patients', models.ManyToManyField(to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
