# Generated by Django 4.1.1 on 2023-08-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_doctor_blood_group_alter_staff_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
