# Generated by Django 4.1.1 on 2023-08-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_doctor_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')]),
        ),
    ]
