# Generated by Django 4.1.1 on 2023-07-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='lab_test',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='report_file',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='is_admited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='is_outdoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='is_surgery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='is_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='lab_tests',
            field=models.ManyToManyField(related_name='medical_reports', to='administrations.labtest'),
        ),
    ]
