# Generated by Django 4.1.1 on 2023-07-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0003_remove_medicalreport_lab_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='patient',
        ),
        migrations.AlterField(
            model_name='ward',
            name='occupancy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
