# Generated by Django 4.1.1 on 2023-08-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0004_remove_bed_patient_alter_ward_occupancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='purpose',
            new_name='symptoms',
        ),
    ]
