# Generated by Django 4.1.1 on 2023-08-04 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0005_rename_purpose_appointment_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='department',
        ),
        migrations.AddField(
            model_name='ward',
            name='contact_number',
            field=models.CharField(default=datetime.datetime(2023, 8, 4, 5, 34, 11, 285453, tzinfo=datetime.timezone.utc), max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='department_name',
            field=models.CharField(default=datetime.datetime(2023, 8, 4, 5, 35, 53, 259125, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='head_of_department',
            field=models.CharField(default=datetime.datetime(2023, 8, 4, 5, 37, 5, 458106, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
