# Generated by Django 4.1.1 on 2023-08-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0007_remove_bed_is_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
