# Generated by Django 4.1.1 on 2023-08-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patient_allocated_bed'),
        ('administrations', '0008_bed_is_occupied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='ward',
        ),
        migrations.AddField(
            model_name='bed',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
