# Generated by Django 4.1.1 on 2023-08-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0009_remove_bed_ward_bed_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrations.ward'),
        ),
    ]
