# Generated by Django 4.1.1 on 2023-08-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0011_prescription_test_alter_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='patient',
        ),
    ]
