# Generated by Django 4.1.1 on 2023-08-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0013_remove_medicalreport_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
