# Generated by Django 4.1.1 on 2023-08-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patient_allocated_bed_patient_ward'),
        ('administrations', '0014_medicalreport_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField()),
                ('appointment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('MedicalReport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.AddField(
            model_name='ward',
            name='fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
