# Generated by Django 4.1.1 on 2023-08-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0015_invoice_ward_fee_delete_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
