# Generated by Django 4.1.1 on 2023-08-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0018_invoice_final_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bed',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
