# Generated by Django 4.1.1 on 2023-08-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0019_appointment_is_paid_bed_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='appointments',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='administrations.appointment'),
        ),
    ]
