# Generated by Django 4.1.1 on 2023-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0020_invoice_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='medical_reports',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='administrations.medicalreport'),
        ),
    ]
