# Generated by Django 4.1.1 on 2023-08-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0021_invoice_medical_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='admission_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='administrations.bed'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
