# Generated by Django 4.1.1 on 2023-08-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0022_invoice_admission_date_invoice_admission_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='patient',
        ),
    ]
