# Generated by Django 4.1.1 on 2023-08-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0023_remove_bed_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bed',
        ),
    ]
