# Generated by Django 4.1.1 on 2023-09-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0024_remove_invoice_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='custom_data',
            field=models.JSONField(default=dict),
        ),
    ]
