# Generated by Django 4.1.1 on 2023-09-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0025_invoice_custom_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Discount_flat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
