# Generated by Django 4.1.1 on 2023-07-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontract',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patient.emergencycontract'),
        ),
    ]
