# Generated by Django 4.1.1 on 2023-07-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0004_remove_bed_patient_alter_ward_occupancy'),
        ('patient', '0002_remove_emergencycontract_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allocated_bed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrations.bed'),
        ),
        migrations.AddField(
            model_name='patient',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
