# Generated by Django 4.1.1 on 2023-08-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patient_allocated_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allocated_bed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ward',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
