# Generated by Django 4.1.1 on 2023-08-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patient_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_gender',
            field=models.CharField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')]),
        ),
    ]
