# Generated by Django 4.1.1 on 2023-08-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_patient_emergency_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_gender',
            field=models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=1),
        ),
    ]
