# Generated by Django 4.1.1 on 2023-08-29 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0023_remove_bed_patient'),
        ('patient', '0011_alter_patient_emergency_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ward',
        ),
        migrations.AlterField(
            model_name='patient',
            name='allocated_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrations.bed'),
        ),
    ]
