# Generated by Django 4.1.1 on 2023-09-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_patient_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
